spring:
  cloud:
    gateway:
      routes:
#        - id: test_route
#          uri: https://www.tieba.com
#          predicates:
#            - Query=url,tieba
#
#        - id: google_route
#          uri: https://www.google.com
#          predicates:
#            - Query=url,google

        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: third_party_route
          uri: lb://mall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
